platform:ios, 7.0
target "pieceSample" do 
pod 'UIActivityIndicator-for-SDWebImage'
pod 'AFNetworking', '2.6.3'
pod 'Reachability'
pod 'SVProgressHUD', '~> 1.0'
pod 'Google/Analytics', '~> 1.0.0'
pod 'UIColor+MLPFlatColors'
end

